@host = https://localhost:7174

GET {{host}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3Y2Q1OGI3Yy1mMWMwLTRhNjEtODc2Yy01Zjk1Yzg0M2NkYjAiLCJqdGkiOiIzZWY5OGJlNC1kM2IzLTRmZjMtYWFiYS1lZDIzM2E2YThkZTIiLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzUyMTYwNywiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.yDdtn7IR718uACdmZpi4MU_BMYepAAzBEHw7f5vHf4E