@host = https://localhost:7174

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Yuri",
    "lastName": "Brasiliano",
    "email": "yuribra2siliano37@gmail.com",
    "password": "123321"
}