@host = https://localhost:7174

POST {{host}}/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YWJiOGMzZC05YTk5LTQwMTQtYjdkYi04MWI4MzBhZDk3MDQiLCJqdGkiOiIwMGQwNGFlMy0xYmRhLTQ0MTEtOWJlMC1kMGI1MGIxODE5NzgiLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzUzNDM0NCwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.CdNhXiFNbr5wao9KP0o1itfXFFPFSNSkTOoUkpQWyWc

{
    "Name" : "9999",
    "UserId" : "814da07f-f28e-4e90-bc2f-5a123738f45d",
    "Description" : "Develop an IU app using Angular",
    "TaskLocation" : "Online",
    "TaskLink" : "None",
    "TaskGroup" : "Alone",
    "TaskDateTime": "2023-05-07T16:00:00"
}