@host = https://localhost:7174
@id = 8abb8c3d-9a99-4014-b7db-81b830ad9704

DELETE {{host}}/jobs/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YWJiOGMzZC05YTk5LTQwMTQtYjdkYi04MWI4MzBhZDk3MDQiLCJqdGkiOiIwMGQwNGFlMy0xYmRhLTQ0MTEtOWJlMC1kMGI1MGIxODE5NzgiLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzUzNDM0NCwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.CdNhXiFNbr5wao9KP0o1itfXFFPFSNSkTOoUkpQWyWc