@host = https://localhost:7174
@id = a14c1022-4e0c-46c6-8acc-0c822f88f9f2

DELETE {{host}}/jobs/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOWIzZGI3MC04MzFmLTQ4NjAtYmY1NC1hMjM1MzkxNzYwYmUiLCJqdGkiOiJiZTE4MjZjNS0zMzNhLTRiMzEtOTUxMS0yNTdhMTZjZDg5MjciLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzUyMjE0OSwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.iIF3UkefzplpC-1k4pc6HfMq8yvzSYtvfOhIpT7MITg

{
    "name" : "Create UI for Hahn",
    "description" : "Develop an IU app using Angular",
    "taskLocation" : "Online",
    "taskLink" : "None",
    "taskGroup" : "Alone",
    "registerDateTime" : "2023-05-07T16:00:00",
    "taskDateTime": "2023-05-07T16:00:00"
}