@host = https://localhost:7174
@id = 2942eb1e-6cc4-4996-bfa5-8bc107708247

GET {{host}}/jobs/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZmI0ZTU0NC1jNTAzLTRlZmUtOTY5NS1hNGE3NDI1MjA2OGEiLCJqdGkiOiI3M2M2N2Q0ZC05ZTI0LTQ1NzAtOWVhMi01MDZkNzUyYzAxMTUiLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzU1ODg2NSwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.JGpUKEOFT-uyuDt2LZkSl8g_Kf2wTKxvMKVev5WU-Iw