@host = https://localhost:7174
@id = eb4a744d-15d9-4609-ab06-9b28e131aafb

GET {{host}}/jobs/{{id}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwOWIzZGI3MC04MzFmLTQ4NjAtYmY1NC1hMjM1MzkxNzYwYmUiLCJqdGkiOiJiZTE4MjZjNS0zMzNhLTRiMzEtOTUxMS0yNTdhMTZjZDg5MjciLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzUyMjE0OSwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.iIF3UkefzplpC-1k4pc6HfMq8yvzSYtvfOhIpT7MITg