@host = https://localhost:7174


GET {{host}}/jobs/usertasks/8abb8c3d-9a99-4014-b7db-81b830ad9704
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZjgxZjQ4NC03ZGU3LTQ5YzQtYWQwZC1lY2E5ZTYzMGYzNWIiLCJqdGkiOiIxZGQxMDdlZC1lZGIwLTRjMTctOTlmNi00NGQ4NWJiMWE4MjYiLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzUzMTA2MSwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.FOyv94lJIfbHHpj-Zp-_QrrLXjcZvtNvhYJS3BCjLTA
