@host = https://localhost:7174


GET {{host}}/jobs/usertasks/2dbe8c2c-f4b2-4ff6-b7f6-7efc606ea2a9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZGZkOGU3Ni0xOTZhLTQxMTEtYmM2OC1iOWJjODc3MGEwNWYiLCJqdGkiOiIwNmJlM2M0YS03MTFlLTQ0Y2YtYTA4Mi0wNzAzNzAxMGQ4YmYiLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzU2NDM3OSwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.whminvTv60pLh98zYKBkPgCRKMgi87ZuUFctzqJuwc0