@host = https://localhost:7174

GET {{host}}/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MjI3MjE5My04Y2IyLTQ3ZDYtODZkYy1kNDQzZDIxNTE5OGQiLCJqdGkiOiJkOWQxOGY3Mi01MWJlLTRjZDktODA4ZS0zZmNhNjQxMjU3MTEiLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzQ2OTczMiwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.1JHEQvO9iTr7K4sSXFglpQ2NuK-vDegZv5X_ojuyDHc