@host = https://localhost:7174

GET {{host}}/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YTBkZTRiYi01ZDliLTQxNTQtODg4My1iNDY3NWI1ODY3MTMiLCJqdGkiOiJjODUyMTA3My00OTY3LTRkNTYtYTcwZS1kOGIzY2UzMDBlMDQiLCJnaXZlbl9uYW1lIjoiWXVyaSIsImZhbWlseV9uYW1lIjoiQnJhc2lsaWFubyIsImV4cCI6MTY4MzQ3Mzk5OSwiaXNzIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIiwiYXVkIjoiSGFobl9Tb2Z0d2FyZWVudHdpY2tsdW5nIn0.PYdvJt9oPY5neGSGznMRUIJNt7IJNlay3RmNO4HdBCc